#pragma once
#include <stdint.h>

namespace agi {

enum class CommandType {
    kArithmetic,
    kResourceManagement,
    kProgramControl,
    kObjectDescription,
    kObjectMotion,
    kInventoryItem,
    kPictureManagement,
    kSoundManagement,
    kTextManagement,
    kStringManagement,
    kInitialization,
    kMenuManagement,
    kOther
};

enum class ActionCommand {
    kReturn             = 0x00,
    kIncrement          = 0x01,
    kDecrement          = 0x02,
    kAssignN            = 0x03,
    kAssignV            = 0x04,
    kAddN               = 0x05,
    kAddV               = 0x06,
    kSubN               = 0x07,
    kSubV               = 0x08,
    kLIndirectV         = 0x09,
    kRIndirect          = 0x0A,
    kLIndirectN         = 0x0B,
    kSet                = 0x0C,
    kReset              = 0x0D,
    kToggle             = 0x0E,
    kSetV               = 0x0F,
    kResetV             = 0x10,
    kToggleV            = 0x11,
    kNewRoom            = 0x12,
    kNewRoomV           = 0x13,
    kLoadLogics         = 0x14,
    kLoadLogicsV        = 0x15,
    kCall               = 0x16,
    kCallV              = 0x17,
    kLoadPic            = 0x18,
    kDrawPic            = 0x19,
    kShowPic            = 0x1A,
    kDiscardPic         = 0x1B,
    kOverlayPic         = 0x1C,
    kShowPriScreen      = 0x1D,
    kLoadView           = 0x1E,
    kLoadViewV          = 0x1F,
    kDiscardView        = 0x20,
    kAnimateObj         = 0x21,
    kUnanimateAll       = 0x22,
    kDraw               = 0x23,
    kErase              = 0x24,
    kPosition           = 0x25,
    kPositionV          = 0x26,
    kGetPosN            = 0x27,
    kReposition         = 0x28,
    kSetView            = 0x29,
    kSetViewV           = 0x2A,
    kSetLoop            = 0x2B,
    kSetLoopV           = 0x2C,
    kFixLoop            = 0x2D,
    kReleaseLoop        = 0x2E,
    kSetCel             = 0x2F,
    kSetCelV            = 0x30,
    kLastCel            = 0x31,
    kCurrentCel         = 0x32,
    kCurrentLoop        = 0x33,
    kCurrentView        = 0x34,
    kNumberOfLoops      = 0x35,
    kSetPriority        = 0x36,
    kSetPriorityV       = 0x37,
    kReleasePriority    = 0x38,
    kGetPriority        = 0x39,
    kStopUpdate         = 0x3A,
    kStartUpdate        = 0x3B,
    kForceUpdate        = 0x3C,
    kIgnoreHorizon      = 0x3D,
    kObserveHorizon     = 0x3E,
    kSetHorizon         = 0x3F,
    kObjectOnWater      = 0x40,
    kObjectOnLand       = 0x41,
    kObjectOnAnything   = 0x42,
    
    kIgnoreObjects      = 0x43,
    kObserveObjects     = 0x44,
    kDistance           = 0x45,
    kStopCycling        = 0x46,
    kStartCycling       = 0x47,
    kNormalCycle        = 0x48,
    kEndOfLoop          = 0x49,
    kReverseCycle       = 0x4A,
    kReverseLoop        = 0x4B,
    kCycleTime          = 0x4C,
    kStopMotion         = 0x4D,
    kStartMotion        = 0x4E,
    kStepSize           = 0x4F,
    kStepTime           = 0x50,
    kMoveObj            = 0x51,
    kMoveObjV           = 0x52,
    kFollowEgo          = 0x53,
    kWander             = 0x54,
    kNormalMotion       = 0x55,
    kSetDir             = 0x56,
    kGetDir             = 0x57,
    kIgnoreBlocks       = 0x58,
    kObserveBlocks      = 0x59,
    kBlock              = 0x5A,
    kUnblock            = 0x5B,
    kGet                = 0x5C,
    kGetV               = 0x5D,
    kDrop               = 0x5E,
    kPut                = 0x5F,
    kPutV               = 0x60,
    kGetRoomV           = 0x61,
    kLoadSound          = 0x62,
    kSound              = 0x63,
    kStopsound          = 0x64,
    kPrint              = 0x65,
    kPrintV             = 0x66,
    kDisplay            = 0x67,
    kDisplayV           = 0x68,
    kClearLines         = 0x69,
    kTextscreen         = 0x6A,
    kGraphics           = 0x6B,
    kSetCursorChar      = 0x6C,
    kSetTextAttribute   = 0x6D,
    kShakeScreen        = 0x6E,
    kConfigureScreen    = 0x6F,
    kStatusLineOn       = 0x70,
    kStatusLineOff      = 0x71,
    kSetString          = 0x72,
    kGetstring          = 0x73,
    kWordToString       = 0x74,
    kParse              = 0x75,
    kGetNum             = 0x76,
    kPreventInput       = 0x77,
    kAcceptInput        = 0x78,
    kSetKey             = 0x79,
    kAddToPic           = 0x7A,
    kAddToPicV          = 0x7B,
    kStatus             = 0x7C,
    kSaveGame           = 0x7D,
    kRestoreGame        = 0x7E,
    kInitDisk           = 0x7F,
    kRestartGame        = 0x80,
    kShowObj            = 0x81,
    kRandom             = 0x82,
    kProgramControl     = 0x83,
    kPlayerControl      = 0x84,
    kObjectStatusV      = 0x85,
    kQuit               = 0x86,
    kShowMem            = 0x87,
    kPause              = 0x88,
    kEchoLine           = 0x89,
    kCancelLine         = 0x8A,
    kInitJoy            = 0x8B,
    kToggleMonitor      = 0x8C,
    kVersion            = 0x8D,
    kScriptSize         = 0x8E,
    kSetGameId          = 0x8F,
    kLog                = 0x90,
    kSetScanStart       = 0x91,
    kResetScanStart     = 0x92,
    kRepositionTo       = 0x93,
    kRepositionToV      = 0x94,
    kTraceOn            = 0x95,
    kTraceInfo          = 0x96,
    kPrintAt            = 0x97,
    kPrintAtV           = 0x98,
    kDiscardViewV       = 0x99,
    kClearTextRect      = 0x9A,
    kSetUpperLeft       = 0x9B,
    kSetMenu            = 0x9C,
    kSetMenuItem        = 0x9D,
    kSubmitMenu         = 0x9E,
    kEnableItem         = 0x9F,
    kDisableItem        = 0xA0,
    kMenuInput          = 0xA1,
    kShowObjectV        = 0xA2,
    kOpenDialogue       = 0xA3,
    kCloseDialogue      = 0xA4,
    kMulN               = 0xA5,
    kMulV               = 0xA6,
    kDivN               = 0xA7,
    kDivV               = 0xA8,
    kCloseWindow        = 0xA9,
    kMax
};

CommandType GetCommandType(uint8_t command);

const char* GetCommandName(uint8_t index);

} // namespace agi
